# Generated by Django 2.0.3 on 2018-03-10 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pizza_app', '0002_loaddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzaorder',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pizzasize',
            name='size',
            field=models.CharField(choices=[('XL', 'Large'), ('MD', 'Medium'), ('SM', 'Small')], max_length=2),
        ),
    ]
